<?php
function cards_menu() {
    $friends = array('Stacy', 'Tracy', 'Macy');
    $items= array();
    foreach ($friends as $friend_name) {
        $items[$friend_name] = array(
            'title' => $friend_name,
            'page callback' => 'friend_greeting',
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
    }
    return $items;
}

function friend_greeting() {
    return '<h2>Hello friend!</h2>';
}
