<?php

function sum_menu() {
    $items['sum'] = array(
        'title' => 'Calculate Sum',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('sum_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['success']=array(
            'title' => "Success",
            'type' => MENU_CALLBACK,
            'access callback' => TRUE,
            'page callback' => 'sum_success',
    );
    return $items;
}

function sum_form() {
    $form['left_number'] = array(
        '#title' => 'Left number',
        '#type' => 'textfield',
        '#description' => t('Please enter your starting number.'),
    );

    $form['right_number'] = array(
        '#title' => 'Right number',
        '#type' => 'textfield',
        '#description' => t('Please enter your next number to add.'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Calculate Sum',
    );

    return $form;
}

function sum_form_submit($form, &$form_state) {
    $first_number = $form_state['values']['left_number'];
    $second_number = $form_state['values']['right_number'];
    $sum = $first_number + $second_number;
    $_SESSION['sum_output'] = $sum;
    $form_state['redirect']= 'success';
}

function sum_success() {
    $answer = $_SESSION['sum_output'];
    return 'You calculated a sum! The answer is: ' . $answer;
}
