<?php
function queen_attack_menu() {
    $items['queen_attack'] = array(
        'title' => "Queen Attack Calculator"
        'page callback' => 'drupal_get_form',
        'page arguments' => array('queen_attack_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function queen_attack_form() {

    $form['queen_position'] = array(
        '#title' => 'Queen Position',
        '#type' => 'textfield',
        '#description' => t("Choose the coordinate of the queen's position"),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );

    return $form;
}

function queen_attack_form_submit($form, &$form_state) {
    $form_state['redirect'] = 'queen_attack_success_page';
}
