<?php
function comment_buddy_menu() {
    $items = array();
    $items['comment_added'] = array(
        'title' => 'Comment Added',
        'page callback' => 'comment_added_message',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['comment_edited'] = array(
        'title' => 'Comment Edited',
        'page callback' => 'comment_edited_message',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['comment_deleted'] = array(
        'title' => 'Comment Deleted',
        'page callback' => 'comment_deleted_message',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
}

function comment_added_message() {
    return '<p>Your comment has been added.</p>';
}

function comment_edited_message() {
    return '<p>Your comment has been updated.</p>';
}

function comment_deleted_message() {
    return '<p>Your comment has been deleted.</p>';
}
//
function comment_buddy_comment_insert() {
    drupal_set_message("Thank you! Comment submitted!");
}
function comment_buddy_comment_update() {
    drupal_set_message("Your comment has been changed.");
}
function comment_buddy_comment_delete() {
    drupal_set_message("Comment deleted. Good work eating your words." );
}
